apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJqZnJvZ2Nsb3VkYWNjb3VudC5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWkc5amEyVnlkWE5sY2pwelFVa3hRRXRTU1ZOSVRrRT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson